#!/bin/sh

PNGFILE="tmp.png"
PDFFILE="texput.pdf"

function preview() {
    convert -density 300 -trim -antialias $PDFFILE -quality 100  $PNGFILE
    sxiv $PNGFILE
}

# -shell-escape is needed for minted
# && zathura tmp/texput.pdf
python src/algorithm2python/main.py | python src/algorithm2python/prepare.py | tee tmp/tmp.tex | pdflatex -shell-escape -output-directory tmp
