#!/bin/sh

PNGFILE="tmp.png"
PDFFILE="texput.pdf"

function preview() {
    convert -density 300 -trim -antialias $PDFFILE -quality 100  $PNGFILE
    sxiv $PNGFILE
}

# -shell-escape is needed for minted
./main.py 2>/dev/null | ./prepare.py | tee tmp.tex | pdflatex -shell-escape && zathura texput.pdf
